import os
os.system('cls')
print("Greenhill : 10")
print("Portal:5.33")
print("Total students:240")
print("Boys:120")
print("031")
print("3.561E+02")
print("Welcome to")
print("Greenhill School")
print('I\nLove\tGreenhill')
